apiVersion: v1
kind: Service
metadata:
  name: bookwork-api
  namespace: bookwork
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: bookwork-api
    app.kubernetes.io/part-of: bookwork
    app.kubernetes.io/component: api
spec:
  selector:
    app: bookwork-api
  ports:
    # This service exposes port 80, which will route to the container's port 8080
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080