apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- namespace.yaml
- grafana-github-oauth-sealed-secret.yaml
- observability-auth-sealed-secret.yaml
- ingress.yaml
- prometheus
- alertmanager
- grafana

commonLabels:
  app.kubernetes.io/part-of: bookwork-observability
  app.kubernetes.io/managed-by: argocd

patches:
- target:
    kind: Deployment
    name: grafana
  patch: |-
    - op: add
      path: /metadata/annotations/app.argoproj.io~1instance
      value: bookwork-observability
- target:
    kind: Deployment
    name: prometheus
  patch: |-
    - op: add
      path: /metadata/annotations/app.argoproj.io~1instance
      value: bookwork-observability
- target:
    kind: Deployment
    name: alertmanager
  patch: |-
    - op: add
      path: /metadata/annotations/app.argoproj.io~1instance
      value: bookwork-observability