---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: bookwork-observability
spec:
  encryptedData:
      admin-password: AgB9GFmVBrb0Sz2UgH+85ciap0LHEiJkT3VO8k/dqo4k2AYsXh3lV0sFzoLcf427U5ID3r7P1iOsxmmFbVNsE4F4awEMa3xqNPy3/SkgdWNXDgDVNqIixr4wVOIdqXkWDAafx8Jmt7QwaNf8SwGxhSuisnCchw2RC675iGa2SD0uHfdD0L565ikYAcIJvDKLMJImr7WrJJBmt4HAp7BSeqMhzLwp6F1ZmpmM8icGrznPupKA/+I+fT6k17FRyx17g7Y9V7fIc8XJ/1WLP0XCpx/3Jxk6Zw9/1tU6EREtEOqWEJwcI2ghr9/q8PQul433TL/+Em2HDVNINsLfZUEsfq0hWqtZdQCDi6SYOZDRBl3+vOG8n6o1uPyaPkTN2qhu/VwhQ8z4NDqw39DedHh28cS9WLLvrnLzrjcp+f/BQCB7WVhfnmJdaQax3UFXeqJjynsjT9OD+445vPKwagD+h2Oa48/hTqJUR7+dhcrGKCrzhnhWvfwXbwkYBlz0/eNZTS/8VcmdexJcjJL+qjF8velCvVR2JrZVuLHR0HvgIlZCWHXcssp2z1WRy7khqdZm8j5GIFUF6avcVJg7Dd/b2A0rqdpjuyQm8NBn5DcKE/HO7Mrc28z5MYPJV7n/oMD6rBvgb4iTAmtom7mAUO2JQaQeIMqd/HvhaGdM1XQu43nYddNspMSSYAYGNUeMnS1fNECcO2O3h/w6mQ==
      admin-user: AgC4HcJI7Auxiyy34NooXwDWEROKlIghnRd/Ftc/e3Jy7H81VIY0aVeay/FVYzssymPuKByh23o1PILWH/ykTHHkKjaBhrhfUappjGBWUvBhzVSMkjVmZA0N1eEyLoYTdKArlP1gMV0Ei32E0mYnnKpF9q8UV1q6OoKQQ3vFJtgWJFGy45hoIITdV93WcM167eu1kzPyXkgXp9Wwpby6pUR1S00d53pKX5R8tmnMHfB480Woi/LvDP+0suo2L01jXfForLKjGFRi/H/MHPgNW/jQYBmjd7WAyNT43LzossJHE/rgR/y0cSztu6ykxLVWypDpsyqAEzNjGFesqL7g0T+mm+RFqAfpVaRkW3Rtl0XGr3KxCREJinMawLqLRQ0OCOVDGTUsOL8sVeJZq2IObPaxYeuhl2MMDEyO43Abc8+3UJ3UdRtshaAAsSF7qyhrWnKvN5y1AV7m2U9mWihgBJOC97DEmqpDOyYT9nIIeERjxUyZ/VuacUcKXQwDzfakfcPEfLmcGOSZW+bejPjkYOFZ6hZnzuKSDu6rJ7UIaq14B+5xvoC0dOadssTUSAYyW7BmYX3zb93qdteIKQmrDQfO1jPLa6W+WcZN1+6pGHGwBqXUIz8l30AhaTbsyJM/1XscwsYWd/YzopOYsoXmr/rfmKefpDSz66ePawnAlGb7b+qfiY2AGEx6MjVZmvoZTj2E4FDovg==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
