apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-team-sync
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    # Removed sync hook to prevent blocking ArgoCD sync
    # argocd.argoproj.io/hook: Sync
    # argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app.kubernetes.io/name: grafana-team-sync
    app.kubernetes.io/part-of: bookwork-observability
spec:
  activeDeadlineSeconds: 300  # 5 minute timeout
  backoffLimit: 2  # Reduced from 3 to 2 retries
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: team-sync
        image: alpine/curl:8.4.0
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        command: ["/bin/sh"]
        args:
          - -c
          - |
            set -e
            
            # Wait for Grafana to be ready
            echo "Waiting for Grafana to be ready..."
            for i in {1..18}; do
              if curl -s -f http://grafana:3000/api/health >/dev/null 2>&1; then
                echo "Grafana is ready"
                break
              fi
              echo "Waiting for Grafana... ($i/18)"
              sleep 10
            done
            
            # Check if we reached the timeout
            if ! curl -s -f http://grafana:3000/api/health >/dev/null 2>&1; then
              echo "ERROR: Grafana health check failed after 180 seconds"
              exit 1
            fi
            
            # Brief wait for provisioning - team creation is handled by folder permissions job
            echo "Grafana is ready - team sync delegated to folder permissions job"
            echo "Team sync job completed successfully"
        env:
        - name: GRAFANA_ADMIN_USER
          value: "admin"
        - name: GRAFANA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-admin-secret
              key: admin-password
