apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-team-sync
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app.kubernetes.io/name: grafana-team-sync
    app.kubernetes.io/part-of: bookwork-observability
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: team-sync
        image: alpine/curl:8.4.0
        command: ["/bin/sh"]
        args:
          - -c
          - |
            set -e
            
            # Wait for Grafana to be ready
            echo "Waiting for Grafana to be ready..."
            for i in {1..30}; do
              if curl -s -f http://grafana:3000/api/health >/dev/null 2>&1; then
                echo "Grafana is ready"
                break
              fi
              echo "Waiting for Grafana... ($i/30)"
              sleep 10
            done
            
            # Wait additional time for provisioning to complete
            echo "Waiting for provisioning to complete..."
            sleep 30
            
            echo "Team sync job completed - team creation handled by folder permissions job"
        env:
        - name: GRAFANA_ADMIN_USER
          value: "admin"
        - name: GRAFANA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-admin-secret
              key: admin-password
  backoffLimit: 3
