apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  acme:
    email: fl_marin@hotmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-account-key
    # Add a single challenge solver, HTTP01, configured to work with NGINX.
    solvers:
      - http01:
          ingress:
            class: nginx