apiVersion: v1
kind: Namespace
metadata:
  name: bookwork
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: "Delete=false"
  labels:
    name: bookwork
    managed-by: argocd