---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: bookwork-observability
data:
  grafana.ini: |
    [server]
    http_port = 3000
    root_url = https://grafana.bookwork-demo.com
    
    [database]
    type = sqlite3
    
    [security]
    disable_gravatar = true
    
    [users]
    allow_sign_up = true
    auto_assign_org = true
    auto_assign_org_role = Viewer
    viewers_can_edit = false
    editors_can_admin = false
    
    [auth]
    disable_login_form = false
    
    [auth.anonymous]
    enabled = false
    
    [auth.github]
    enabled = true
    allow_sign_up = true
    client_id = ${GF_AUTH_GITHUB_CLIENT_ID}
    client_secret = ${GF_AUTH_GITHUB_CLIENT_SECRET}
    scopes = user:email,read:org
    auth_url = https://github.com/login/oauth/authorize
    token_url = https://github.com/login/oauth/access_token
    api_url = https://api.github.com/user
    # Allow any GitHub user to sign up and get viewer access
    allowed_organizations = 
    team_ids = 
    role_attribute_path = 
    # Grant viewer access to GitHub users for dashboard viewing
    auto_assign_org_role = Viewer
    # Disable admin assignment via GitHub OAuth
    allow_assign_grafana_admin = false
    # Skip organization member API calls for better compatibility
    skip_org_role_update_sync = false
    
    [log]
    mode = console
    level = info
    
    [log.console]
    level = info
    format = json
    
    [metrics]
    enabled = true
    
    [alerting]
    enabled = false
    
    [unified_alerting]
    enabled = true
    
    [feature_toggles]
    enable = ngalert
    
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/bookwork-infrastructure.json
    
    [database]
    wal = true
    
    [server]
    serve_from_sub_path = false
    
    [plugins]
    allow_loading_unsigned_plugins = 
    
    [live]
    max_connections = 100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: bookwork-observability
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
      jsonData:
        timeInterval: "5s"
        queryTimeout: "300s"
        httpMethod: "GET"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: bookwork-observability
data:
  dashboard-providers.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      editable: false
      updateIntervalSeconds: 30
      allowUiUpdates: false
      options:
        path: /var/lib/grafana/dashboards
        foldersFromFilesStructure: false