---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: bookwork-observability
spec:
  encryptedData:
      admin-password: AgCz1IGe1JImrqQJI2PfaIxcAru+cQHJCW/6K0NOzstTOqsLSAb+05AvDjwnbFe32ZB9t10zuhWFJwjpVr42lVOgRahGGNvELhPoVE4gwlU2CuVmmf3wMzL9xqIUJYLqAJ5jHwUT8DrUfKHbGAp/5LQmJlzI3BUdlimolpM9CeHYr1MrJ9zDtMq5JbPLH/G+XKFh4FJWEYvGmzmU9YzqRvkQpE6vCTH38cWsPVd5IbAG00i38b6lHb9gTrr++Gu9owfnB6aYCXcyWPFhA7NvxVbFDa207SAS9axz1bj28czFti42tZZjrlYddG330HEH2YKNuMXR8xq0Tk7iX3YIu7sl6M3X6yiozqJqnOBBC9P0EfOM+DizeYmCR3s7UmDPJ0vuXceYw/AZnKRxMK5vGV+klrhgeDZqjq5A5xyEJA8jfSymCG1hokl6SAB0y1RzwVdXJuES3n6V+WLrpKzuHs4843bDDtZ1uqQpvrniS4JB/R86ZvozBTfQikPHWDr7MdPQZ2uDulVbqrz0g3e7CnkDPoMghMd8Sjcr8erZsORxtCNBPvQNAigYH/MM9djQa6mDUpfopeIif4YQh26ZMldlUFqdEW10PLv+WI75CITcn0vFAplhRx7Rq3OLqbfREBGL1qtqoQbQEpI7sPStE6pp6XwGv3KuxVUltbC6kXZdsSu/F7usSGawr8YoLrhrI+WgMJ5RMH8mrAQjg+KHpaLoVYKl
      admin-user: AgCcQvYJDd2y62iJ24XGGGIwRBKk3lqnOUzmS6/EIpfvDRzJDhAb8/+P9q2tF7PWuUnA1BVr+xEdE5dD/f8dveEkV9T11fUYH/OzVlrMXFVTiOr/D9wmYh6na6uWEEW6cw0cKvYINxVRfNeTMGn2BIIeSrlRQ5qo4k+vLrHTanAWy7h3yNYyzCfne4SFogWrmwWKAnqcGI3ZEcbNgZlTK+Y6oogAwL6BJL/PIW1BYfbo+UrKnYLcTXfK/MQUhjAa5/9yuKmUv1tTzWs6jXFSbN4yggPMssaNr7I9/y8KVHVvsTv9uySvGDz8DR8xnVHolUpKl23j8rjIWfExyGTnVcl+rHyHEsNhciVuSViO+vMdLHzrb+fjjxDJa75xAfJaqdqRTQ90E0IhbG8jJa596fjC0YMSWY4efyLuMnD0TGVoGTtcuqg4K5aLQPGSx5Dl6q25hdTHe5hMJ2F7ZAZU618dH8FhOUFmY2Oc6nZypGbQDtGlinIaZIUy+uPxeIxgEgN/ZjnqHZNUVRL0rG+Bprwa+1dXMoAJPT9zHmGyAuXdnEZSAg88hAwcVFGn75hTUsddR3Ud6bHPI+nqL375izIuvUJRW/YQ0p+SmYPO5I/KkDZoV/JyDwzDghsFncvfkNEhC/YxcoFI8F+J15kBB4Q1/S1siwZqj6MFLdsTK6WlJszMzKXBzwoZCBm/WO5rQsuMx3e3hQ==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
