apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- namespace.yaml
- grafana-github-oauth-sealed-secret.yaml
- observability-auth-sealed-secret.yaml
- ingress.yaml
- prometheus
- alertmanager
- grafana