---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: observability-auth
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: observability-auth
    app.kubernetes.io/part-of: bookwork-observability
spec:
  encryptedData:
    auth: AgC6OsMBZR6WHz9RUWridr0e9C4hRo9iys83ozTxg5KEMg+//S+QGy1G1xccm+vJ+TUVhlhdLQ6QvylM632U0bNH9/yqFn3PWsT0z5EkOUczEMVjBlkMERhD+2c4ftTPy6OMLstkF/MyZXuMHZytJRzlxWYZGLLpGSWTmmiwBsH+AwNGgUUoodmwrQZBylzXGWwYtzIiiDQVmmktzKcKP4uWDpVHbLJm2CTD/WPyvDTae9P+gVUhCR7+UYuFQ3og5k9cxi//6IZwIkorPSNDZLP70yVmzpVNHJ1zi4VjbQnb7PhXPwQPxW3TKlqkjEiZ/SIsxqMlZwHCzNqRTAbsBvvF/b3356m15ShL+Kgq2A3fM8nrg06lXxoFRaLQMtvYe9wbL9dt8c7HIHZy9CZNG939UDwrABhY16W8OxMJPubh/PEHDJB4H3QsvYgyR8cN8EcY+jMhFyzifUlfq1rA3hQ2Kl3X6hBGrbuZGxYZ0/U4JI+XmRysKtYdv9YaFdC+1A2MmhHNixKSRqNVKGiH75v62C1plIiPedoJA0RDpWJHOsK/AQRTfdeVg6xdssD0aUHvdf6uQ4r6rzWkhCrd1Wdx07SYmU45a+YZuhJX+HeWJVWKRYsA1vlsfNhe33ERqPc4lJJNehHcWuqE2lxpaQhh7MImaoaIK37Qw92X3mVjR172ZBclLz3tAGeHfUK5LFHQlN5WcPUhSKjL/eMqz9FWIlBaRvFshFpsrKwdzxywxNztbxdIxQIY41H+FQpoeABUDLYuFpXqXfJnhAwCbMBsdOA=
  template:
    metadata:
      name: observability-auth
      namespace: monitoring
    type: Opaque
