---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: observability-auth
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: observability-auth
    app.kubernetes.io/part-of: bookwork-observability
spec:
  encryptedData:
    auth: AgAXOTtBlGn1/Fy0zgpI1LG1CTKB3S4X69LN0NpGGNi1log9EQ1VE7awXWNLaUj1fEWma9dlkP1mWo7Rk09E//JnYZCPVR8F1UWdXZwqH5ckbOVEGaZN26PG2NQzfdkmwf1tQOz6WZ3V96t0e0gvTlxGZgi258dFvcfkh8YVV8aI/L10MR1fljOnrtlbgvthRfl1LgqRAXoiqL3HtKJgYR8BA9zX9CU+LY6B6X7fnT+Dhf90IPl0ympWIDFkzGgbXkiKS6eLqnDT2waNFmwDMzMjMuKva2arjCXtK+vEbPTb08zVgZrkBi/+kybmuvwDg7recCnFe+a64fRUsb1ASpBRrRQWFB3FciESHcX0VgYoo40MoMXNzaUBbiGAowFB+qoHXeI88dQ/vyzlYBoummPwbZi1L3Uc/FVpatvaaWnZNYZIiKhbwR6yev+pP50IDONToDJDO25BqEt9Dyqrio/S9s+G3jiXgnuhoHZYhF70NqGojhQsZh9/kDen1JAqa+pl35iA8yvGFw+pimzlSw7bRH6EO2ogyeCp/wQEoTf/dl5bvohK14bCHI+1g/OU+xTaOxPAj7yEoMEvMtiOt2QdS+XTB5XhGSSsxJrLPtntCtSvWLVJ79s8OfpAoAmTcAyRSpAU27e4APWhkmXX0vxrYkFgqWP6GsVH5/d/8oP1UK96nTMHyV5hg8EDEbVr5xJdPFC4OihnK/9sVUpwQDjaAOaqWVAqaQMerO20XKarU2jNiHJZyR11AQUt
  template:
    metadata:
      name: observability-auth
      namespace: monitoring
    type: Opaque
