apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookwork-api
  namespace: bookwork
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookwork-api
  template:
    metadata:
      labels:
        app: bookwork-api
        app.kubernetes.io/name: bookwork-api
        app.kubernetes.io/part-of: bookwork
        app.kubernetes.io/component: api
        argocd.argoproj.io/instance: bookwork-api
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: api
          #use a symbolic name that Kustomize will replace
          image: bookwork-api
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20