---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-secrets
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: bookwork-observability
spec:
  encryptedData:
    # Slack webhook URL for notifications
    slack-webhook-url: AgCbgBH1Mek4aeUkGhov6FYRQ1pZqvFbY5VjxEGDolF09SMldTQ99b1MUMxHqVSYOnYx6bDKhkiJKIbOjCq1pWj30b7K6xJ14SPE/X8ZddOpLGavi6QFqK2lZmIqsDQz9zKvqMKPZRyQQ5ybuXYLumxCkrGZeIPkVSw+mGEkt+YGCaMeFMaGLpkFUS4/k5v//79FCZm143hTtEEXTE8G9Hr4xzrNjfNG1lL0fJcv0DP/IxfnoiR9WX6/VJNSQTi2hDkT6VmlAzE5GV5KssiCL+ZARrsPA1xO9r6bq2sMm5RHaVnkW0v0NcmuxKHJijekoz8hc94eX0mG82nobynXUyiVzXr0J+KDswu9jIlWu/4LStrkdjdi/ilE+H3rqQtMKk6XGVKntysxnxMi/J47j1vZfvXJ7q3Bk8DI8NTqGRAHmcyDgVPiFZZ0NMxqqY098HfLfQZo6rKt7NkX/FV3rxw8zEXf4cMeNuQWmyyjL1B8NqHo++PPcpxyU56+EmjIzJy7lxPBC4iIhK9jFL/bIv5QC/sX7jButhsXJeI+KY18VHyYp1iK0mA3RlMv8JUkETtH+C0KxaXp2zATyuta3VHavtr3QhSjJBkpGmwkaqMJKpnIgvPsucMszJtFS/StIB/ipPt9uA/oAgafjkMTdiRyudg/SDWKqP77VmhkaqkEsdnX+fLOAzZ/ve+QrruioH9izNdIpQZ6uz/+F5roi/X5Q5KFEwUIGajETSIiydv9IY8PZ4jtSh0QyF+/V9YBYcEVpg==
  template:
    metadata:
      name: alertmanager-secrets
      namespace: monitoring
      labels:
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/part-of: bookwork-observability
    type: Opaque
