---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookwork-api
  namespace: argocd
  labels:
    app.kubernetes.io/name: bookwork-api
    app.kubernetes.io/part-of: bookwork
    app.kubernetes.io/component: api
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "C0958PSUQ74"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "C0958PSUQ74"
    notifications.argoproj.io/subscribe.on-health-degraded.slack: "C0958PSUQ74"
    notifications.argoproj.io/subscribe.on-out-of-sync.slack: "C0958PSUQ74"
    notifications.argoproj.io/subscribe.on-created.slack: "C0958PSUQ74"
    notifications.argoproj.io/subscribe.on-deleted.slack: "C0958PSUQ74"
    notifications.argoproj.io/subscribe.on-app-restored.slack: "C0958PSUQ74"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bookwork
  source:
    repoURL: 'https://github.com/hazyView/bookwork-gitops.git'
    path: manifests/bookwork/base/components/api
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bookwork
  syncPolicy:
    automated:
      prune: false  # Manual sync for API for more control
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  info:
    - name: 'Sync Wave'
      value: '5'
    - name: 'Purpose'
      value: 'Bookwork API backend service'
    - name: 'Status'
      value: 'Currently disabled in production - deployment commented out'
