apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookwork-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hazyView/bookwork-gitops.git'
    path: tenants/bookwork/base
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bookwork
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true