apiVersion: v1
kind: Service
metadata:
  name: bookwork-frontend
  namespace: bookwork
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/instance: bookwork-frontend
  labels:
    app.kubernetes.io/name: bookwork-frontend
    app.kubernetes.io/part-of: bookwork
    app.kubernetes.io/component: frontend
    argocd.argoproj.io/instance: bookwork-frontend
spec:
  selector:
    app: bookwork-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 80
  