---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: bookwork-observability
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - name: web
      protocol: TCP
      port: 9093
      targetPort: 9093
