---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules-frontend
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: bookwork-observability
data:
  frontend-rules.yml: |
    groups:
      - name: bookwork-frontend.rules
        interval: 30s
        rules:
          # ============================================================================
          # SLO/SLI BASED ALERTS - Service Level Objectives
          # ============================================================================
          
          - alert: BookworkSLOErrorRateCritical
            expr: (sum(rate(bookwork_frontend_http_requests_total{status=~"5.."}[1h])) / sum(rate(bookwork_frontend_http_requests_total[1h]))) > 0.01
            for: 2m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
              slo: availability
              burn_rate: fast
            annotations:
              summary: "Bookwork SLO: Critical error rate breach"
              description: "Error rate {{ $value | humanizePercentage }} exceeds SLO threshold of 1% over 1h window. This consumes error budget rapidly."
              runbook_url: "https://wiki.bookwork.com/runbooks/slo-error-rate"

          - alert: BookworkSLOErrorRateWarning
            expr: (sum(rate(bookwork_frontend_http_requests_total{status=~"5.."}[6h])) / sum(rate(bookwork_frontend_http_requests_total[6h]))) > 0.005
            for: 15m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
              slo: availability
              burn_rate: medium
            annotations:
              summary: "Bookwork SLO: Elevated error rate"
              description: "Error rate {{ $value | humanizePercentage }} exceeds SLO threshold of 0.5% over 6h window."

          - alert: BookworkSLOLatencyCritical
            expr: histogram_quantile(0.95, rate(bookwork_frontend_http_request_duration_seconds_bucket[5m])) > 1.0
            for: 2m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
              slo: latency
            annotations:
              summary: "Bookwork SLO: Critical latency breach"
              description: "95th percentile latency {{ $value | humanizeDuration }} exceeds SLO threshold of 500ms."
              runbook_url: "https://wiki.bookwork.com/runbooks/slo-latency"

          - alert: BookworkSLOLatencyWarning
            expr: histogram_quantile(0.95, rate(bookwork_frontend_http_request_duration_seconds_bucket[15m])) > 0.5
            for: 10m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
              slo: latency
            annotations:
              summary: "Bookwork SLO: Elevated latency"
              description: "95th percentile latency {{ $value | humanizeDuration }} exceeds warning threshold."

          - alert: BookworkSLOAvailabilityCritical
            expr: (1 - (sum(rate(bookwork_frontend_http_requests_total{status=~"5.."}[1h])) / sum(rate(bookwork_frontend_http_requests_total[1h])))) < 0.999
            for: 5m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
              slo: availability
            annotations:
              summary: "Bookwork SLO: Availability below 99.9%"
              description: "Service availability {{ $value | humanizePercentage }} is below SLO target of 99.9%."

          - alert: BookworkErrorBudgetExhaustion
            expr: (sum(increase(bookwork_frontend_http_requests_total{status=~"5.."}[30d])) / sum(increase(bookwork_frontend_http_requests_total[30d]))) > 0.001
            for: 0m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
              slo: error_budget
            annotations:
              summary: "Bookwork SLO: Error budget 90% consumed"
              description: "Error budget consumption is at {{ $value | humanizePercentage }} for the 30-day window. Consider implementing service improvements."

          # ============================================================================
          # NODE.JS SPECIFIC ALERTS
          # ============================================================================
          
          - alert: BookworkNodeJSEventLoopLag
            expr: bookwork_frontend_nodejs_eventloop_lag_p99_seconds > 0.1
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
              component: nodejs
            annotations:
              summary: "Bookwork Node.js: High event loop lag"
              description: "Node.js event loop lag P99 is {{ $value | humanizeDuration }}. This indicates blocking operations affecting performance."
              runbook_url: "https://wiki.bookwork.com/runbooks/nodejs-eventloop"

          - alert: BookworkNodeJSMemoryLeak
            expr: increase(bookwork_frontend_nodejs_active_handles_total[1h]) > 100
            for: 15m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
              component: nodejs
            annotations:
              summary: "Bookwork Node.js: Potential memory leak detected"
              description: "Active handles increased by {{ $value }} in the last hour. This may indicate a memory leak."

          # ============================================================================
          # HIGH AVAILABILITY ALERTS
          # ============================================================================
          
          - alert: BookworkFrontendDown
            expr: up{job="bookwork-frontend"} == 0
            for: 1m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend is down"
              description: "Bookwork Frontend has been down for more than 1 minute. No metrics are being scraped from {{ $labels.instance }}."
              runbook_url: "https://wiki.bookwork.com/runbooks/frontend-down"

          - alert: BookworkFrontendPodCrashLooping
            expr: rate(kube_pod_container_status_restarts_total{container="frontend",namespace="bookwork"}[5m]) > 0
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend pod is crash looping"
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently."

          - alert: BookworkFrontendReplicasDown
            expr: kube_deployment_status_replicas_available{deployment="bookwork-frontend",namespace="bookwork"} < kube_deployment_spec_replicas{deployment="bookwork-frontend",namespace="bookwork"}
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend has fewer replicas than desired"
              description: "Deployment {{ $labels.deployment }} has {{ $value }} available replicas out of {{ $labels.spec_replicas }} desired."

          # ============================================================================
          # PERFORMANCE ALERTS
          # ============================================================================

          - alert: BookworkFrontendHighCPUUsage
            expr: (rate(container_cpu_usage_seconds_total{container="frontend",namespace="bookwork"}[5m]) * 100) > 80
            for: 10m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend high CPU usage"
              description: "Frontend container CPU usage is above 80% for more than 10 minutes. Current usage: {{ $value }}%"

          - alert: BookworkFrontendHighMemoryUsage
            expr: (container_memory_working_set_bytes{container="frontend",namespace="bookwork"} / container_spec_memory_limit_bytes{container="frontend",namespace="bookwork"} * 100) > 85
            for: 10m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend high memory usage"
              description: "Frontend container memory usage is above 85% for more than 10 minutes. Current usage: {{ $value }}%"

          - alert: BookworkFrontendMemoryLeak
            expr: increase(container_memory_working_set_bytes{container="frontend",namespace="bookwork"}[1h]) > 100*1024*1024
            for: 2h
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Potential memory leak in Bookwork Frontend"
              description: "Frontend container memory usage increased by {{ $value }} bytes in the last hour."

          # ============================================================================
          # APPLICATION SPECIFIC ALERTS (Application Metrics)
          # ============================================================================

          - alert: BookworkFrontendHighErrorRate
            expr: (sum(rate(error_count{job="bookwork-frontend"}[5m])) / sum(rate(request_count{job="bookwork-frontend"}[5m])) * 100) > 2
            for: 5m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend high error rate"
              description: "Frontend application error rate is {{ $value }}% which is above the 2% threshold."

          - alert: BookworkFrontendHighLatency
            expr: histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{job="bookwork-frontend"}[5m])) by (le)) > 1
            for: 10m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend high latency"
              description: "95th percentile application latency is {{ $value }}s which is above 1s threshold."

          - alert: BookworkFrontendLowTraffic
            expr: sum(rate(request_count{job="bookwork-frontend"}[5m])) < 0.1
            for: 30m
            labels:
              severity: info
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend unusually low traffic"
              description: "Frontend is receiving less than 6 requests per minute for 30 minutes."

          - alert: BookworkFrontendHighComponentErrors
            expr: sum(rate(bookwork_frontend_component_errors_total{job="bookwork-frontend"}[5m])) > 0.1
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend component errors detected"
              description: "Frontend components are experiencing errors at {{ $value }} errors/sec."

          - alert: BookworkFrontendSlowComponentLoading
            expr: histogram_quantile(0.95, sum(rate(bookwork_frontend_component_load_duration_seconds_bucket{job="bookwork-frontend"}[5m])) by (le, component)) > 1
            for: 10m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend slow component loading"
              description: "Component {{ $labels.component }} is taking more than 1s to load (P95: {{ $value }}s)."

          - alert: BookworkFrontendLowCacheHitRate
            expr: (sum(rate(bookwork_frontend_cache_hits_total{job="bookwork-frontend"}[5m])) / (sum(rate(bookwork_frontend_cache_hits_total{job="bookwork-frontend"}[5m])) + sum(rate(bookwork_frontend_cache_misses_total{job="bookwork-frontend"}[5m])))) * 100 < 70
            for: 15m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend low cache hit rate"
              description: "Cache hit rate is {{ $value }}% which is below the 70% threshold."

          - alert: BookworkFrontendHighRateLimitHits
            expr: sum(rate(bookwork_frontend_rate_limit_hits_total{job="bookwork-frontend"}[5m])) > 1
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend hitting rate limits"
              description: "Frontend is hitting rate limits at {{ $value }} hits/sec."

          - alert: BookworkFrontendSecurityEvents
            expr: sum(rate(bookwork_frontend_security_events_total{job="bookwork-frontend"}[5m])) > 0
            for: 1m
            labels:
              severity: critical
              service: bookwork-frontend
              team: security
            annotations:
              summary: "Bookwork Frontend security events detected"
              description: "Security events detected: {{ $value }} events/sec. Event types: {{ $labels.event_type }}."

          - alert: BookworkFrontendSessionsHigh
            expr: bookwork_frontend_active_sessions{job="bookwork-frontend"} > 1000
            for: 10m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend high session count"
              description: "Active sessions count is {{ $value }}, which is above the 1000 threshold."

          # ============================================================================
          # FALLBACK NGINX INGRESS ALERTS (Secondary monitoring)
          # ============================================================================

          - alert: BookworkFrontendNginxHighErrorRate
            expr: (rate(nginx_ingress_controller_requests{service="bookwork-frontend",status=~"5.."}[5m]) / rate(nginx_ingress_controller_requests{service="bookwork-frontend"}[5m]) * 100) > 2
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend NGINX high error rate"
              description: "Frontend NGINX error rate is {{ $value }}% which is above the 2% threshold (fallback alert)."

          - alert: BookworkFrontendNginxHighLatency
            expr: histogram_quantile(0.95, rate(nginx_ingress_controller_request_duration_seconds_bucket{service="bookwork-frontend"}[5m])) > 1
            for: 10m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend NGINX high latency"
              description: "95th percentile NGINX latency is {{ $value }}s which is above 1s threshold (fallback alert)."

          # ============================================================================
          # INFRASTRUCTURE ALERTS
          # ============================================================================

          - alert: BookworkFrontendPodNotReady
            expr: kube_pod_status_ready{condition="false",namespace="bookwork",pod=~"bookwork-frontend-.*"} == 1
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend pod not ready"
              description: "Pod {{ $labels.pod }} has been in not-ready state for more than 5 minutes."

          - alert: BookworkFrontendPVCSpaceWarning
            expr: (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~".*frontend.*"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~".*frontend.*"} * 100) < 20
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend PVC running low on space"
              description: "PVC {{ $labels.persistentvolumeclaim }} has less than 20% free space remaining."

          # ============================================================================
          # BUSINESS LOGIC ALERTS
          # ============================================================================

          - alert: BookworkFrontendDeploymentStuck
            expr: kube_deployment_status_condition{deployment="bookwork-frontend",namespace="bookwork",condition="Progressing",status="false"} == 1
            for: 15m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend deployment is stuck"
              description: "Deployment {{ $labels.deployment }} is not progressing and may be stuck."

          - alert: BookworkFrontendImagePullError
            expr: kube_pod_container_status_waiting_reason{container="frontend",namespace="bookwork",reason="ImagePullBackOff"} == 1
            for: 5m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend cannot pull container image"
              description: "Pod {{ $labels.pod }} cannot pull the frontend container image."

          # ============================================================================
          # RECOVERY ALERTS
          # ============================================================================

          - alert: BookworkFrontendRecovered
            expr: up{job="bookwork-frontend"} == 1
            for: 1m
            labels:
              severity: info
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend has recovered"
              description: "Bookwork Frontend service {{ $labels.instance }} is now responding to health checks."

          # ============================================================================
          # MEMORY LEAK DETECTION
          # ============================================================================

          - alert: BookworkFrontendMemoryLeakDetected
            expr: increase(container_memory_working_set_bytes{container="frontend",namespace="bookwork"}[2h]) > 200*1024*1024
            for: 1h
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Memory leak detected in Bookwork Frontend"
              description: "Memory usage has increased by {{ $value | humanize1024 }} over the last 2 hours, indicating a potential memory leak."
