---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules-frontend
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: bookwork-observability
data:
  frontend-rules.yml: |
    groups:
      - name: bookwork-frontend.rules
        interval: 30s
        rules:
          # ============================================================================
          # HIGH AVAILABILITY ALERTS
          # ============================================================================
          
          - alert: BookworkFrontendDown
            expr: up{job="bookwork-frontend"} == 0
            for: 1m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend is down"
              description: "Bookwork Frontend has been down for more than 1 minute. No metrics are being scraped from {{ $labels.instance }}."
              runbook_url: "https://wiki.bookwork.com/runbooks/frontend-down"

          - alert: BookworkFrontendPodCrashLooping
            expr: rate(kube_pod_container_status_restarts_total{container="frontend",namespace="bookwork"}[5m]) > 0
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend pod is crash looping"
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently."

          - alert: BookworkFrontendReplicasDown
            expr: kube_deployment_status_replicas_available{deployment="bookwork-frontend",namespace="bookwork"} < kube_deployment_spec_replicas{deployment="bookwork-frontend",namespace="bookwork"}
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend has fewer replicas than desired"
              description: "Deployment {{ $labels.deployment }} has {{ $value }} available replicas out of {{ $labels.spec_replicas }} desired."

          # ============================================================================
          # PERFORMANCE ALERTS
          # ============================================================================

          - alert: BookworkFrontendHighCPUUsage
            expr: (rate(container_cpu_usage_seconds_total{container="frontend",namespace="bookwork"}[5m]) * 100) > 80
            for: 10m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend high CPU usage"
              description: "Frontend container CPU usage is above 80% for more than 10 minutes. Current usage: {{ $value }}%"

          - alert: BookworkFrontendHighMemoryUsage
            expr: (container_memory_working_set_bytes{container="frontend",namespace="bookwork"} / container_spec_memory_limit_bytes{container="frontend",namespace="bookwork"} * 100) > 85
            for: 10m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend high memory usage"
              description: "Frontend container memory usage is above 85% for more than 10 minutes. Current usage: {{ $value }}%"

          - alert: BookworkFrontendMemoryLeak
            expr: increase(container_memory_working_set_bytes{container="frontend",namespace="bookwork"}[1h]) > 100*1024*1024
            for: 2h
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Potential memory leak in Bookwork Frontend"
              description: "Frontend container memory usage increased by {{ $value | humanizeBytes }} in the last hour."

          # ============================================================================
          # APPLICATION SPECIFIC ALERTS (HTTP/NGINX based)
          # ============================================================================

          - alert: BookworkFrontendHighErrorRate
            expr: (rate(nginx_ingress_controller_requests{service="bookwork-frontend",status=~"5.."}[5m]) / rate(nginx_ingress_controller_requests{service="bookwork-frontend"}[5m]) * 100) > 5
            for: 5m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend high error rate"
              description: "Frontend error rate is {{ $value }}% which is above the 5% threshold."

          - alert: BookworkFrontendHighLatency
            expr: histogram_quantile(0.95, rate(nginx_ingress_controller_request_duration_seconds_bucket{service="bookwork-frontend"}[5m])) > 2
            for: 10m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend high latency"
              description: "95th percentile latency is {{ $value }}s which is above 2s threshold."

          - alert: BookworkFrontendLowTraffic
            expr: rate(nginx_ingress_controller_requests{service="bookwork-frontend"}[5m]) < 0.1
            for: 30m
            labels:
              severity: info
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend unusually low traffic"
              description: "Frontend is receiving less than 6 requests per minute for 30 minutes."

          # ============================================================================
          # INFRASTRUCTURE ALERTS
          # ============================================================================

          - alert: BookworkFrontendPodNotReady
            expr: kube_pod_status_ready{condition="false",namespace="bookwork",pod=~"bookwork-frontend-.*"} == 1
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend pod not ready"
              description: "Pod {{ $labels.pod }} has been in not-ready state for more than 5 minutes."

          - alert: BookworkFrontendPVCSpaceWarning
            expr: (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~".*frontend.*"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~".*frontend.*"} * 100) < 20
            for: 5m
            labels:
              severity: warning
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend PVC running low on space"
              description: "PVC {{ $labels.persistentvolumeclaim }} has less than 20% free space remaining."

          # ============================================================================
          # BUSINESS LOGIC ALERTS
          # ============================================================================

          - alert: BookworkFrontendDeploymentStuck
            expr: kube_deployment_status_condition{deployment="bookwork-frontend",namespace="bookwork",condition="Progressing",status="false"} == 1
            for: 15m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend deployment is stuck"
              description: "Deployment {{ $labels.deployment }} is not progressing and may be stuck."

          - alert: BookworkFrontendImagePullError
            expr: kube_pod_container_status_waiting_reason{container="frontend",namespace="bookwork",reason="ImagePullBackOff"} == 1
            for: 5m
            labels:
              severity: critical
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend cannot pull container image"
              description: "Pod {{ $labels.pod }} cannot pull the frontend container image."

          # ============================================================================
          # RECOVERY ALERTS
          # ============================================================================

          - alert: BookworkFrontendRecovered
            expr: up{job="bookwork-frontend"} == 1
            for: 1m
            labels:
              severity: info
              service: bookwork-frontend
              team: frontend
            annotations:
              summary: "Bookwork Frontend has recovered"
              description: "Bookwork Frontend service {{ $labels.instance }} is now responding to health checks."
