---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-slack-bridge
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: alertmanager-slack-bridge
    app.kubernetes.io/part-of: bookwork-observability
spec:
  type: ClusterIP
  selector:
    app: alertmanager-slack-bridge
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
