apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookwork
resources:
- components/infrastructure
- components/frontend
- components/api
# Commented out resource avoid DB costs
#- ../../components/api/api/deployment.yaml
#- ../../components/api/service.yaml
images:
- name: bookwork-api
  newName: us-central1-docker.pkg.dev/bookwork-466915/bookwork-registry/bookwork-api
  newTag: 6fb3352
- name: us-central1-docker.pkg.dev/bookwork-466915/bookwork-registry/bookwork-frontend
  newTag: 5ff93a4
