---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-secrets
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: bookwork-observability
spec:
  encryptedData:
    # Slack webhook URL for notifications
    slack-webhook-url: AgATIovV4+LJfYnd/Py/S92b/nvvuVLGKQbw79QuDE2SPdrbL1+tr4lRtsNag7Z9N94bEvHbRGFdNI46feT4rfW7WfDMHg66nBKOXmm8Ult/10ajlB3jY6n420BYpOhczLEA1nbXzjtBZidzMgKxIkqsxhUPMG2ewMWXOvupxYibww7TyrSeLhKZzVMcWrU37rGXDjy+4m0nOMfADRMZPAu9aUhm2NEAMnQ0hiyXlZBrb7QNOLw31WqxAniZolA9p1z2cgn3cV4ex9/NAyN2F6RntsrIVlDW8yAHuxd1xErlOXm9I9gvYQCo8mB4ipdRozRNA19jd/klEaZ6Or31OYW8v+ge9VGt7q4UauFH6XUJEvgqgT84Hgb6CG/GrIU60dgfeyiADXeMxuAeP2RfgetQ6Pty93QtI/5dXeTHt4X6CYdjhcLR1IbHu93z+fgGODtDpMVWnKVXl7qjCbX+Y85JS3HOybB9DEGSdYP2+cVajgcNED36MGjz4/1vvkHkVG4pgYePq5IJJvCZVNnUUxeC7mXnku3GnhXKy8qv7HwspsqJ3VASCwgbrFeH9FA8xL7P+4RSCnGYP2mBnRSGPyUsDUSQHhXw+9L8Db7tl3/+WaEYy4BIUYhpBHMswbu35r1kKfm7ro4pKqQHfxx+mb08b40EJ5YUCNzCZSsoIPkWqYP/tt9l/8h3RoC1kOrlcXzuedhWPud4JIFRlzq8GsF8A/sRARHGFw3edbQd59FzSOaj3eUzFCMOyf/EvoX4v3rOwHJIdyPZ4Km90NjhrkzQoKOZOk7RUB7P8gkOrKJAQZs=
  template:
    metadata:
      name: alertmanager-secrets
      namespace: monitoring
      labels:
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/part-of: bookwork-observability
    type: Opaque
